// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Subsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.mach.LightDrive.*;  //The LightDrive Library
import java.awt.Color;         //Predefined colors and routines

/**
 *
 */
public class LightDrive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private LightDrivePWM ld_pwm;

    public LightDrive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        //PWM Servo Controlled LightDrive (specify 2 WPI Servo objects)
        Servo servo0 = new Servo(8);
        Servo servo1 = new Servo(9);
        ld_pwm = new  LightDrivePWM(servo0, servo1);

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void setStringColor( int string, String color) {
        //ld_object: ld_can, ld_serial, or ld_pwm.
       //Set Bank 1 to Red, Bank 2 to yellow, Bank 3 to custom.
       if (color == "Red") {
        ld_pwm.SetColor(string, Color.red);
       } else if (color == "Blue") {
        ld_pwm.SetColor(string, Color.blue);
       } else if (color == "Yellow") {
        ld_pwm.SetColor(string, Color.yellow);
       } else if (color == "Green") {
        ld_pwm.SetColor(string, Color.green);
       } else {
           ld_pwm.SetColor(string, Color.pink);
       }
       //Send latest colors to LightDrive
       ld_pwm.Update();

    }


    public void setStringColor( int string, Color color) {
        //ld_object: ld_can, ld_serial, or ld_pwm.
       //Set Bank 1 to Red, Bank 2 to yellow, Bank 3 to custom.
       ld_pwm.SetColor(1, Color.red);
       ld_pwm.SetColor(2, Color.yellow);
       ld_pwm.SetColor(3, Color.blue);
       ld_pwm.SetColor(4, Color.green);
       //Send latest colors to LightDrive
       ld_pwm.Update();

    }

}

